name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main # Or your desired branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build Docker Image
        run: docker build . --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/image-name

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository_owner }}/image-name